image: nixos/nix:latest

before_script:
  - nix-channel --add https://nixos.org/channels/nixpkgs-unstable nixpkgs
  - nix-channel --update
  - apk --update add ca-certificates
  - nix-env -f "<nixpkgs>" -i bash stack
  - stack setup
  - stack build

build:
  script:
    - stack test

coverage:
  script:
    - nix-env -f "<nixpkgs>" -i curl
    - stack install codecov-haskell
    - stack test --coverage
    - codecov-haskell lithium-tests
  allow_failure: true
