image: nixos/nix:latest

stages:
  - build
  - coverage

before_script:
  - nix-channel --add https://nixos.org/channels/nixpkgs-unstable nixpkgs
  - nix-channel --update
  - apk --update add ca-certificates
  - nix-env -f "<nixpkgs>" -i bash stack
  - stack setup
  - stack build

build:
  stage: build
  script:
    - stack test

coverage:
  stage: coverage
  script:
    - nix-env -f "<nixpkgs>" -iA git
    - git clone https://github.com/jlengyel/codecov-haskell
    - stack install ./codecov-haskell
    - stack test --coverage
    - codecov-haskell lithium-tests
  allow_failure: true
