language: nix

before_install:
  - nix-env -f "<nixpkgs>" -i bash stack

install:
  - stack setup

script:
  - stack test

afer_success:
  - nix-env -f "<nixpkgs>" -iA git xz gnumake
  - git clone https://github.com/jlengyel/codecov-haskell
  - cd codecov-haskell
  - stack install .
  - cd ..
  - stack test --coverage --haddock
  - codecov-haskell lithium-tests
