language: nix

before_install:
  - nix-env -f "<nixpkgs>" -i bash stack

install:
  - stack setup
  - stack build

script:
  - stack test

afer_success:
  - git clone https://github.com/jlengyel/codecov-haskell ../codecov-haskell
  - stack install ../codecov-haskell
  - stack test --coverage --haddock
  - codecov-haskell lithium-tests
