language: nix

before_install:
  - nix-env -f "<nixpkgs>" -iA bash stack git xz gnumake
  - git clone https://github.com/eth-r/codecov-haskell
  - cd codecov-haskell
  - stack install .
  - cd ..

install:
  - stack setup

script:
  # - stack test
  - stack test --coverage --haddock
  - stack exec "codecov-haskell lithium-tests"

# afer_success:
#   - nix-env -f "<nixpkgs>" -iA git xz gnumake
#   - git clone https://github.com/jlengyel/codecov-haskell
#   - cd codecov-haskell
#   - stack install .
#   - cd ..
