# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
name: lithium
version: '0.0.0'
github: "eth-r/lithium"
license: PublicDomain
author: "Promethea Raschke"
maintainer: "Promethea Raschke"
synopsis: "Cryptography that's slightly less likely to blow up on you"
description: "Lithium is a Libsodium wrapper aiming to remove all unnecessary and dangerous choices"
category: Crypto

extra-libraries:
  - sodium

extra-source-files:
  - CHANGELOG.md
  - LICENSE
  - package.yaml
  - README.md
  - stack.yaml

library:
  default-extensions:
    - NoImplicitPrelude
    - OverloadedStrings
  ghc-options:
    - -Wall
    - -Werror
  exposed-modules:
    - Crypto.Lithium.Aead
    - Crypto.Lithium.Box
    - Crypto.Lithium.Hash
    - Crypto.Lithium.Password
    - Crypto.Lithium.Random
    - Crypto.Lithium.SecretBox
    - Crypto.Lithium.Sign
    - Crypto.Lithium.Types
    - Crypto.Lithium.Unsafe.Aead
    - Crypto.Lithium.Unsafe.Box
    - Crypto.Lithium.Unsafe.Hash
    - Crypto.Lithium.Unsafe.Password
    - Crypto.Lithium.Unsafe.SecretBox
    - Crypto.Lithium.Unsafe.Sign
    - Crypto.Lithium.Unsafe.Types
  other-modules:
    - Crypto.Lithium.Internal.Aead
    - Crypto.Lithium.Internal.Box
    - Crypto.Lithium.Internal.Hash
    - Crypto.Lithium.Internal.Init
    - Crypto.Lithium.Internal.Password
    - Crypto.Lithium.Internal.Random
    - Crypto.Lithium.Internal.SecretBox
    - Crypto.Lithium.Internal.Sign
    - Crypto.Lithium.Internal.Util
    - Crypto.Lithium.Util.Init
    - Crypto.Lithium.Util.Nat
    - Crypto.Lithium.Util.Phantom
    - Crypto.Lithium.Util.Random
    - Crypto.Lithium.Util.Secret
    - Crypto.Lithium.Util.Sized
  dependencies:
    - base
    - basement
    - bytestring
    - deepseq
    - foundation
    - memory

benchmarks:
  lithium-benchmarks:
    source-dirs: bench
    main: Main.hs
    other-modules:
      - BoxBench
      - HashBench
      - RandomBench
    dependencies:
      - base
      - deepseq
      - lithium
      - memory
      - criterion
    ghc-options:
      - -rtsopts
      - -threaded
      - -with-rtsopts=-N
      - -O2

tests:
  lithium-tests:
    source-dirs: test
    main: Main.hs
    other-modules:
      - AeadTest
      - BoxTest
      - HashTest
      - PasswordTest
      - SecretBoxTest
      - SignTest
      - TestUtils
    dependencies:
      - base
      - base16-bytestring
      - bytestring
      - hspec
      - lithium
      - memory
      - QuickCheck
      - tasty
      - tasty-hspec
    ghc-options:
      - -rtsopts
      - -threaded
      - -with-rtsopts=-N
